---
- hosts: servers
  become: true
  become_user: root
  tasks:
          - name: Update packages
            apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

          - name: Curl installation
            apt: 
            pkg:
                    - curl

          - name: UFW conf
            ufw:
                    state: enabled
                    policy: allow
            ufw:
                    rule: allow
                    port: 80,8080,1834

          - name: SSH conf
            linefile: dest=/etc/ssh/sshd_config regexp='#Port 22' line='Port 1834'

          - name: SSH conf episode 2
            linefile: dest=/etc/ssh/sshd_config regexp='#Pubkey Authentication yes' line='Pubkey Authentication yes'
         
          - name: Webdeveloper birth
            user:
                    name: Webdeveloper
                    password: S52we9V6QTp7
                    shell: /bin/bash
                    append: yes
                    generate_ssh_key: yes
                    ssh_key_bits: 2048
                    ssh_key_file: .ssh/id_rsa

          - name: Webdeveloper key
            authorized_key:
                  user: Webdeveloper
                  state: present
                  key: "{{ lookup('file', '/home/Webdeveloper/.ssh/id_rsa.pub') }}"

          - name: Devopsengineer birth
            user:
                    name: Devopsengineer
                    password: dHy6sKGHsj2T
                    shell: /bin/bash
                    append: yes
                    generate_ssh_key: yes
                    ssh_key_bits: 2048
                    ssh_key_file: .ssh/id_rsa

          - name: Devopsengineer key
            authorized_key:
                  user: Devopsengineer
                  state: present
                  key: "{{ lookup('file', '/home/Devopsengineer/.ssh/id_rsa.pub') }}" 
          
          - name: Projectmanager birth
            user:
                    name: Projectmanager
                    password: oP92ugMSaCbe
                    shell: /bin/bash
                    append: yes
                    generate_ssh_key: yes
                    ssh_key_bits: 2048
                    ssh_key_file: /ssh/id_rsa

          - name: Projectmanager key
            authorized_key:
                    user: Projectmanager
                    state: present
                    key: "{{ lookup('file', '/home/Projectmanager/.ssh.id_rsa.pub') }}"

          - name: Docker

          - name: Docker-compose

          - name: skillcloud-nginx

          - name: SSH restart
            service: name=ssh state=restarted

          - name: UFW restart
            service: name=ufw state=restarted

          - name: Reboot
            reboot:

